version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: pnpm install
      - run:
          command: pnpm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
  release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install GitHub CLI
          command: |
            sudo apt-get update && sudo apt-get install -y gh
      - run:
          name: Authenticate GitHub CLI
          command: echo $GH_TOKEN | gh auth login --with-token
      - run:
          name: Create GitHub Release
          command: |
            gh release create v$(date +%Y%m%d%H%M%S) -t "Release $(date)" -n "Automated release by CircleCI"
workflows:
  build_and_release:
    jobs:
      - build-node
      - release:
          requires:
            - build-node
          context: github-release-context
